import type { Theme } from './types';

export const themes: Theme[] = [
  {
    id: 'claude',
    name: 'Claude',
    description: 'Warm dark with elegant serif accents',
    isDark: true,
    font: "'Playfair Display', Georgia, serif",
    colors: {
      background: '#191919',
      surface: '#222222',
      surfaceAlt: '#262626',
      border: '#2c2c2c',
      primary: '#F1ECE4',
      secondary: '#9F998E',
      accent: '#e05c38',
      accentForeground: '#FFFFFF',
      muted: '#635E54',
      danger: '#EF4444',
      success: '#22C55E',
      warning: '#EAB308',
      sidebar: '#141414',
      sidebarBorder: '#222222',
      headerBg: '#191919',
      inputBg: '#222222',
      inputBorder: '#2c2c2c',
      cardBg: '#222222',
      hoverBg: '#2a2a2a',
      tooltipBg: '#2c2c2c',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight Blue',
    description: 'Deep navy futuristic aesthetic',
    isDark: true,
    colors: {
      background: '#0B1121',
      surface: '#141E33',
      surfaceAlt: '#1A2744',
      border: '#1F3361',
      primary: '#F0F4FF',
      secondary: '#A8B6D9',
      accent: '#60A5FA',
      accentForeground: '#FFFFFF',
      muted: '#4F6382',
      danger: '#FC8181',
      success: '#68D391',
      warning: '#F6E05E',
      sidebar: '#080E1A',
      sidebarBorder: '#141E33',
      headerBg: '#0B1121',
      inputBg: '#141E33',
      inputBorder: '#1F3361',
      cardBg: '#141E33',
      hoverBg: '#1A2744',
      tooltipBg: '#1F3361',
    },
  },
  {
    id: 'amoled',
    name: 'AMOLED Black',
    description: 'Pure black for deep contrast',
    isDark: true,
    colors: {
      background: '#000000',
      surface: '#0D0D0D',
      surfaceAlt: '#141414',
      border: '#1F1F1F',
      primary: '#F5F5F5',
      secondary: '#AAAAAA',
      accent: '#BB86FC',
      accentForeground: '#FFFFFF',
      muted: '#505050',
      danger: '#FF5252',
      success: '#4CAF50',
      warning: '#FFC107',
      sidebar: '#000000',
      sidebarBorder: '#0D0D0D',
      headerBg: '#000000',
      inputBg: '#0D0D0D',
      inputBorder: '#1F1F1F',
      cardBg: '#0D0D0D',
      hoverBg: '#141414',
      tooltipBg: '#1F1F1F',
    },
  },
  {
    id: 'light',
    name: 'Light Minimal',
    description: 'Clean white modern productivity',
    isDark: false,
    colors: {
      background: '#FAFAF9',
      surface: '#FFFFFF',
      surfaceAlt: '#F5F5F4',
      border: '#E4E4E7',
      primary: '#1C1C1E',
      secondary: '#8E8E93',
      accent: '#6366F1',
      accentForeground: '#FFFFFF',
      muted: '#D4D4D8',
      danger: '#EF4444',
      success: '#22C55E',
      warning: '#EAB308',
      sidebar: '#F5F5F4',
      sidebarBorder: '#E4E4E7',
      headerBg: '#FAFAF9',
      inputBg: '#FFFFFF',
      inputBorder: '#E4E4E7',
      cardBg: '#FFFFFF',
      hoverBg: '#F5F5F4',
      tooltipBg: '#1C1C1E',
    },
  },
  {
    id: 'cyberpunk',
    name: 'Neon Cyberpunk',
    description: 'Dark UI with neon purple/cyan',
    isDark: true,
    colors: {
      background: '#0A0A0F',
      surface: '#13131F',
      surfaceAlt: '#1A1A2E',
      border: '#2A2A4A',
      primary: '#EEEEFF',
      secondary: '#9D9DBF',
      accent: '#C084FC',
      accentForeground: '#FFFFFF',
      muted: '#4A4A6A',
      danger: '#FF6B6B',
      success: '#34D399',
      warning: '#FBBF24',
      sidebar: '#050508',
      sidebarBorder: '#13131F',
      headerBg: '#0A0A0F',
      inputBg: '#13131F',
      inputBorder: '#2A2A4A',
      cardBg: '#13131F',
      hoverBg: '#1A1A2E',
      tooltipBg: '#2A2A4A',
    },
  },
];

export const defaultThemeId = 'claude';

export function getThemeById(id: string): Theme {
  return themes.find((t) => t.id === id) || themes[0];
}
